### PR TITLE
dependency: Migrate from glide to Go modules

### PR DESCRIPTION
**Pull request by netoax**
What does this implement/fix?
---------------------------------------------------
The Go modules is an official dependency management solution built into the `go` command. It supports the main feature provided by the most used solutions until now such as vendoring and package installation based on semantic versioning. Therefore, this patch removes the glide related files and adds the Go module's package description file and locking file. Moreover, since the previous github.com/cenkalti/backoff package doesn't support Go modules this patch also updates it to version v4.

Where has this been tested?
---------------------------
**Operating System/Platform:** macOS 10.14 - Darwin

**Go Version:** go 1.13.6

### CODE REVIEW

**Comment by netoax** [comment]
The `makefile` must be updated too. I forgot to do it. `make tools` should work fine but `make deps` is still using glide.

**Comment by netoax** [comment]
> The `makefile` must be updated too. I forgot to do it. `make tools` should work fine but `make deps` is still using glide.

Done.

**Review by vitbaq — CHANGES_REQUESTED** [review]
Update the readme with instructions to use go modules.

**Comment by netoax** [comment]
> Update the readme with instructions to use go modules.

Done.

**Review by vitbaq — APPROVED** [review]

**Pull request merged**
