### PR TITLE
refactor:thing: Change authorization-key to authorization-token

### LINKED ISSUE #68: Update 'request data' tests
**What is expected?**

While reading the tests for `request_data`, I expected to see `authorization-token` (as it is throughout Babeltower) as the `authentication` parameter.

**What is actually happening?**

Instead, the `authentication` parameter is `authorization-key`. This leads to having nonstandard code. If a developer is unlucky enough to click on this test file, they might use it as reference and will lead to nonstandard code in other repos as well. 

**Environment:**

- Operating System/Platform: N/A
- Node version: N/A
- Yarn version: N/A
- Babeltower version: N/A

If you have relevant logs, error output and etc, please attach them.

**Other information:**

### PR DESCRIPTION
**Pull request by jsantos93**
**Describe what this PR introduces:** (if necessary, link currently open issues with [special keywords](https://help.github.com/en/articles/closing-issues-using-keywords))

In order to have a code standard, this commit changes the authentication parameter to authorization-token in the interactor test cases. Also changes the string `not passed` to `not provided`

close #68

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce any breaking changes?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Related issues are referenced in the PR (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

**Testing environment:**

- Operating System/Platform:
- Go version:

If you have relevant logs, error output and etc, please attach them.

**Other information:**

### CODE REVIEW

**Review by lcbm — CHANGES_REQUESTED** [review]
Thanks for taking some time to contribute :confetti_ball: :star_struck: 

The patch looks good to me! I noticed there are four other occurrences of `key` (see image below). Also, the `not passed` string should be `not provided`. Would you mind updating these as well? :point_down: 

ArcoLinux-2020-05-01-1588354315_screenshot_1920x1848

**Comment by jsantos93** [comment]
Sure!! I didn't notice that. 🙃

**Comment by lcbm** [comment]
LGTM! Thank you for the contribution :star_struck:

**Review by lcbm — APPROVED** [review]
LGTM! Thank you for the contribution :star_struck:

**Review by esdrasjnr — APPROVED** [review]
Well noticed! Thanks for colaboration and time! LGTM :100: :+1:

**Review by netoax — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
