### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by vitbaq**
What does this implement/fix? Explain your changes
---------------------------------------------------
This PR renames files and structs to be more clear to understand, fixes a data_request subscribe and removes receive register message function on connector delivery.

Does this close any currently open issues?
------------------------------------------
--

Any relevant logs, error output, etc?
-------------------------------------
--

Any other comments\?
-------------------
--

Where has this been tested?
---------------------------

**Operating System/Platform:** Ubuntu 18.04.3 LTS

**Go Version:**  go version go1.13.5 linux/amd64

### CODE REVIEW

**Comment by joaoaneto** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/handler/amqp/msg_handler.go  1
- pkg/thing/delivery/amqp/client.go  2
         

Complexity decreasing per file
==============================
+ pkg/thing/interactors/register_thing.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4984766&bid=16460433)

**Review by esdrasjnr — COMMENTED** [review]
I think that "thing: delivery: **Remove** receive register message" commit title doesn't make such sense. Maybe **Replace** or **Move** explain better the changes, what do you think?

**Review by esdrasjnr — COMMENTED** [review]
LGTM!

**Comment by netoax** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/thing/delivery/amqp/client.go  2
- pkg/thing/handler/amqp/msg_handler.go  1
         

Complexity decreasing per file
==============================
+ pkg/thing/interactors/register_thing.go  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/joaoaneto/knot-babeltower/pullRequest?prid=4984766&bid=16460433)

**Review by ramonhpr — APPROVED** [review]

**Pull request merged**
